function cum = cumulant0(im,n)
switch n
    case 1
        cum = 0;
    case 2
        cum = mean(im(:,:,:,1:end-1).*im(:,:,:,2:end),4);
    case 3
        cum = mean(im(:,:,:,1:end-2).*im(:,:,:,2:end-1).*im(:,:,:,3:end),4);
    case 4
        cum = -mean(im(:,:,:,1:end-3).*im(:,:,:,4:end),4).*mean(im(:,:,:,2:end-2).*im(:,:,:,3:end-1),4)-mean(im(:,:,:,1:end-3).*im(:,:,:,3:end-1),4).*mean(im(:,:,:,2:end-2).*im(:,:,:,4:end),4)-mean(im(:,:,:,1:end-3).*im(:,:,:,2:end-2),4).*mean(im(:,:,:,3:end-1).*im(:,:,:,4:end),4)+mean(im(:,:,:,1:end-3).*im(:,:,:,2:end-2).*im(:,:,:,3:end-1).*im(:,:,:,4:end),4);
  case 5
    cum = -mean(im(:,:,:,4:end-1).*im(:,:,:,5:end),4).*mean(im(:,:,:,1:end-4).*im(:,:,:,2:end-3).*im(:,:,:,3:end-2),4) ...
          -mean(im(:,:,:,3:end-2).*im(:,:,:,5:end),4).*mean(im(:,:,:,1:end-4).*im(:,:,:,2:end-3).*im(:,:,:,4:end-1),4) ...
          -mean(im(:,:,:,3:end-2).*im(:,:,:,4:end-1),4).*mean(im(:,:,:,1:end-4).*im(:,:,:,2:end-3).*im(:,:,:,5:end),4) ...
          -mean(im(:,:,:,2:end-3).*im(:,:,:,5:end),4).*mean(im(:,:,:,1:end-4).*im(:,:,:,3:end-2).*im(:,:,:,4:end-1),4) ...
          -mean(im(:,:,:,2:end-3).*im(:,:,:,4:end-1),4).*mean(im(:,:,:,1:end-4).*im(:,:,:,3:end-2).*im(:,:,:,5:end),4) ...
          -mean(im(:,:,:,2:end-3).*im(:,:,:,3:end-2),4).*mean(im(:,:,:,1:end-4).*im(:,:,:,4:end-1).*im(:,:,:,5:end),4) ...
          -mean(im(:,:,:,1:end-4).*im(:,:,:,5:end),4).*mean(im(:,:,:,2:end-3).*im(:,:,:,3:end-2).*im(:,:,:,4:end-1),4) ...
          -mean(im(:,:,:,1:end-4).*im(:,:,:,4:end-1),4).*mean(im(:,:,:,2:end-3).*im(:,:,:,3:end-2).*im(:,:,:,5:end),4) ...
          -mean(im(:,:,:,1:end-4).*im(:,:,:,3:end-2),4).*mean(im(:,:,:,2:end-3).*im(:,:,:,4:end-1).*im(:,:,:,5:end),4) ...
          -mean(im(:,:,:,1:end-4).*im(:,:,:,2:end-3),4).*mean(im(:,:,:,3:end-2).*im(:,:,:,4:end-1).*im(:,:,:,5:end),4) ...
          +mean(im(:,:,:,1:end-4).*im(:,:,:,2:end-3).*im(:,:,:,3:end-2).*im(:,:,:,4:end-1).*im(:,:,:,5:end),4);

case 6
    cum = 2.*mean(im(:,:,:,1:end-5).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,6:end),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,6:end),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,6:end),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,6:end),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          +2.*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,6:end),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,4:end-2).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,5:end-1).*im(:,:,:,6:end),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4) ...
          -mean(im(:,:,:,4:end-2).*im(:,:,:,6:end),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,3:end-3).*im(:,:,:,6:end),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,3:end-3).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,2:end-4).*im(:,:,:,6:end),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,2:end-4).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,6:end),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,5:end-1),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,4:end-2),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,3:end-3),4).*mean(im(:,:,:,2:end-4).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          -mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4),4).*mean(im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4) ...
          +mean(im(:,:,:,1:end-5).*im(:,:,:,2:end-4).*im(:,:,:,3:end-3).*im(:,:,:,4:end-2).*im(:,:,:,5:end-1).*im(:,:,:,6:end),4);
end

